ritly_app/config/routes.rb
RitlyApp::Application.routes.draw do

  resources  :users, :sessions	

  get '/signup', to: 'users#new'

  delete '/signout', to: 'sessions#destroy'

  get'/signin', to: 'sessions#new'
  
  root to: 'links#index'

  get '/go', to: 'links#index'

  post '/go', to: 'links#create'

  get '/go/:random_string/preview', to: 'links#show', as: 'link_preview'

  get 'go/:random_string', to: 'links#redirect', as: 'link'

end

ritly_app/app/models/link.rb
# == Schema Information
#
# Table name: links
#
#  id            :integer          not null, primary key
#  url           :string(255)
#  random_string :string(255)
#  created_at    :datetime
#  updated_at    :datetime
#

class Link < ActiveRecord::Base

end

ritly_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#  password_digest :string(255)
#

class User < ActiveRecord::Base
    has_secure_password

    before_save :create_remember_token

    private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

ritly_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include SessionsHelper
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ritly_app/app/controllers/links_controller.rb
class LinksController < ApplicationController
	before_filter :signed_in_user, only: [:create, :new, :edit, :update]

	def index
		render :index
	end

	def create
        @random_string = SecureRandom.urlsafe_base64(8) 
        params[:link][:random_string] = @random_string
		link = params.require(:link).permit(:url, :random_string)
	    @link = Link.create(link)
		redirect_to link_preview_path(@link.random_string)
	end

	def show
		@link = Link.find_by(random_string: params[:random_string])
		render :show
	end

	def redirect
		@link = Link.find_by(random_string: params[:random_string])
		redirect_to "http://#{@link.url}"
	end

end

ritly_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
  	signin_params = params[:session]
    user=User.find_by_email(signin_params[:email].downcase)
    if user && user.authenticate(signin_params[:password])
        # Sign the user in and redirect to the user's show page.
        sign_in user
        redirect_to user
    else
        # Create an error message and re-render the signin form.
        flash.now[:error]='Invalid email/password combination'
        render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end 
end

ritly_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def show
  	@user = User.find(params[:id])
  end

  def create
  	user = params.require(:user).permit(:name, :email, :password, :password_confirmation)
    @user = User.create(user)
    if @user.save
        flash[:success] = "Welcome to the Cook Book app!"
        sign_in @user
        redirect_to @user
    else
        render'new'
    end
  end

  def update
  	@user = User.find(params[:id])
    @user.update_attributes(params[:user])
    render :show
  end
end

ritly_app/app/helpers/application_helper.rb
module ApplicationHelper
end

ritly_app/app/helpers/links_helper.rb
module LinksHelper
end

ritly_app/app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    # current_user is avilable in controllers and views!
    # This is an is an assignment, which we must define - see below
    # note that next line is a call to setter 'def current_user=(user)' below
    current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  # Authorization: signed_in_user is called in a before_filter
  # callback in each controller, see books/ingredients/recipe controllers
  # Ensures access to create/edit functions on if signed in.
  def signed_in_user
    unless signed_in?
      # If not signed in, save current location in session object
      # to be able to redirect after successful sign in.
      session[:return_to] = request.url
      # prompt sign in page
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  # signs out user by deleting @current_user and session cookie
  def sign_out
    @current_user = nil
    cookies.delete(:remember_token)
  end

  # Getter and setter for @current_user
  def current_user=(user)
    @current_user = user
  end

  # if current_user doesn't exist, check session cookie for user session
  # If exists, get the user record that belongs to that session.
  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end
end

ritly_app/app/helpers/users_helper.rb
module UsersHelper
end

ritly_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RitlyApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

ritly_app/app/views/links/index.html.erb
<h1>Welcome to Ritly</h1>

<%= form_for :link, url: go_path, method: :post do |f| %>

<%= f.text_field :url, placeholder: "enter a URL" %> <br>

<%= f.submit %>
<% end %>

ritly_app/app/views/links/show.html.erb
<h1>Preview</h1>


<div>
    URL: <%= @link.url %> 
</div>

<div>
    Random String: <%= @link.random_string %> 
</div>

<div>
	<a href="http://localhost:3000/go/<%=@link.random_string%>">Click here</a> to go to your site.
</div>

ritly_app/app/views/users/new.html.erb
<h1>Signup Page</h1>

<div class="row">
    <div class="span6 offset3">

        <%= form_for (@user) do |f| %>
        
        <%= f.label :name %>
		<%= f.text_field :name, placeholder: "enter username" %></br>

		<%= f.label :email %>
		<%= f.text_field :email, placeholder: "enter email" %></br>

		<%= f.label :password %>
		<%= f.text_field :password, placeholder: "enter password" %></br>

		<%= f.label :password_confirmation, "Confirmation" %>
		<%= f.password_field :password_confirmation, placeholder: "confirm password" %></br>

		<%= f.submit "Signup", class: "btn btn-large btn-primary" %></br>
		<% end %>
    </div>
</div>

ritly_app/app/views/users/show.html.erb
<h1>User Profile Page</h1>
<div class="row">
    <aside class="span4">
       <div>
       	Username:
       	<%= @user.name%>
       </div> 

       <div>
       	User Email:
       	<%= @user.email%>
       </div>
    </aside>
</div>